name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux_64:
    runs-on: ubuntu-latest

    env:
      GARRYSMOD_COMMON: ${{ github.workspace }}/garrysmod_common

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies (Premake5)
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
        tar -xvf premake-5.0.0-beta2-linux.tar.gz

    - name: Clone garrysmod_common
      run: |
        git clone https://github.com/danielga/garrysmod_common --recursive --branch=x86-64-support-sourcesdk $GARRYSMOD_COMMON

    - name: Generate makefiles with Premake
      run: |
        ./premake5 gmake

    - name: Build the project
      run: |
        cd projects/linux/gmake
        make config=releasewithsymbols_x86_64
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmsv_xconsole_linux64.dll
        path: ${{ github.workspace }}/projects/linux/gmake/x86_64/ReleaseWithSymbols/gmsv_xconsole_linux64.dll
        
  build_linux:
    runs-on: ubuntu-latest

    env:
      GARRYSMOD_COMMON: ${{ github.workspace }}/garrysmod_common

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies (Premake5)
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
        tar -xvf premake-5.0.0-beta2-linux.tar.gz

    - name: Clone garrysmod_common
      run: |
        git clone https://github.com/danielga/garrysmod_common --recursive $GARRYSMOD_COMMON

    - name: Generate makefiles with Premake
      run: |
        sed -i '' 's/PROJECT_GENERATOR_VERSION = 3/PROJECT_GENERATOR_VERSION = 2/' ./premake.lua
        ./premake5 gmake

    - name: Build the project
      run: |
        cd projects/linux/gmake
        make
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmsv_xconsole_linux.dll
        path: ${{ github.workspace }}/projects/linux/gmake/x86/Release/gmsv_xconsole_linux.dll
        
  build_osx_64:
    runs-on: macos-13

    env:
      GARRYSMOD_COMMON: ${{ github.workspace }}/garrysmod_common

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies (Premake5)
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-macosx.tar.gz
        tar -xvf premake-5.0.0-beta2-macosx.tar.gz
        chmod a+x ./premake5

    - name: Clone garrysmod_common
      run: |
        git clone https://github.com/danielga/garrysmod_common --recursive --branch=x86-64-support-sourcesdk $GARRYSMOD_COMMON

    - name: Generate makefiles with Premake
      run: |
        ./premake5 gmake

    - name: Build the project
      run: |
        cd projects/macosx/gmake
        make config=releasewithsymbols_x86_64
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmsv_xconsole_osx64.dll
        path: ${{ github.workspace }}/projects/macosx/gmake/x86_64/ReleaseWithSymbols/gmsv_xconsole_osx64.dll
